In [2]:
import os
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from scipy.cluster.hierarchy import linkage, fcluster, dendrogram
from scipy.spatial.distance import squareform
from sklearn.metrics import silhouette_score, silhouette_samples
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.cm as cm
import pickle
from pandas.api.types import is_numeric_dtype
from sklearn.model_selection import train_test_split
from scipy.stats import mannwhitneyu
from scipy.spatial.distance import cdist
from sklearn.cluster import MiniBatchKMeans
import re

import sklearn, matplotlib, scipy
import tensorflow as tf
from tensorflow import keras

In [3]:
print(f"NumPy version: {np.__version__}")
print(f"Pandas version: {pd.__version__}")
print(f"Scikit-learn version: {sklearn.__version__}")
print(f"Matplotlib version: {matplotlib.__version__}")
print(f"Seaborn version: {sns.__version__}")
print(f"SciPy version: {scipy.__version__}")
print(f"TensorFlow version: {tf.__version__}")
print(f"Keras version: {keras.__version__}")

NumPy version: 1.24.4
Pandas version: 1.2.4
Scikit-learn version: 1.3.2
Matplotlib version: 3.4.1
Seaborn version: 0.11.1
SciPy version: 1.10.1
TensorFlow version: 2.7.0
Keras version: 2.7.0

In [12]:
# Pandas 출력 옵션 조정 - All
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

In [15]:
# Pandas 출력 옵션 조정 - Default
pd.reset_option('display.max_rows')
pd.reset_option('display.max_columns')
pd.reset_option('display.width')
pd.reset_option('display.max_colwidth')

In [4]:
## Definitions

## Defines

# Data confirmmation :: Nan counts + Nan Ratios, Unique values
def analyse_dataframe(df):
    # NaN 개수, 비율 및 고유 값 개수 계산
    nan_counts = df.isnull().sum()
    nan_ratios = df.isnull().mean() * 100  # 백분율로 표시
    unique_values_count = df.nunique()

    # 결과 데이터 프레임 생성
    analysis_result = pd.DataFrame({
        'NaN Counts': nan_counts,
        'NaN Ratios (%)': nan_ratios,
        'Unique Values Count': unique_values_count
    })

    return analysis_result

def print_progress(iteration, total, prefix='', suffix='', decimals=1, length=50, fill='█', printEnd="\r"):
    """
    Call in a loop to create terminal progress bar
    @params:
        iteration   - Required  : current iteration (Int)
        total       - Required  : total iterations (Int)
        prefix      - Optional  : prefix string (Str)
        suffix      - Optional  : suffix string (Str)
        decimals    - Optional  : positive number of decimals in percent complete (Int)
        length      - Optional  : character length of bar (Int)
        fill        - Optional  : bar fill character (Str)
        printEnd    - Optional  : end character (e.g. "\r", "\r\n") (Str)
    """
    percent = ("{0:." + str(decimals) + "f}").format(100 * (iteration / float(total)))
    filledLength = int(length * iteration // total)
    bar = fill * filledLength + '-' * (length - filledLength)
    print(f'\r{prefix} |{bar}| {percent}% {suffix}', end=printEnd)
    # Print New Line on Complete
    if iteration == total: 
        print()

In [5]:
## Configs
base = '/media/bami/d4960d77-e5f3-4877-a333-26e637be3a0e/JHA/24-07_nedis/KNN'
# out = f'{base}/Clustering/M01_Main'
# out = f'{base}/Clustering/M13/1_Whole'
out = f'{base}/Clustering/M15_dataset08/1_Whole/1_ALL/C4'
ipt = f'{base}/Dataset'

In [6]:
save_dir = out

In [7]:
# DATA IMPORT
df_scd = pd.read_csv(os.path.join(save_dir, f"df_scd_4clustered.csv")
                     , index_col=0
                    )
# df_scd.set_index('idx_code', inplace=True)

df = pd.read_csv(f"{ipt}/knn_prep-fin_M08.csv")
# df = pd.read_csv(f"{ipt}/knn_prep-fin_M08-alive.csv")
df.rename(columns={'Unnamed: 0': 'idx_code'}, inplace=True)
df.set_index('idx_code', inplace=True)

# df_combined = df.join(df_scd['Cluster_Labels'], how='left')


print(df_scd)
print(df)
# print(df_combined)

          sex_sys_val     apgs1     apgs5      bwei      mage      gran  \
idx_code
0                   1 -0.361034 -1.032974  0.867691 -1.020264 -0.760507
1                   1 -0.361034 -1.032974 -1.001814  0.360486 -0.760507
2                   1  0.117458 -0.497525  1.034612 -1.710639 -0.760507
3                   1  0.595950  0.037925  0.834307 -1.710639 -0.760507
4                   1 -0.361034 -1.032974  0.500467  0.590611  1.748735
...               ...       ...       ...       ...       ...       ...
20408               1  0.117458  0.573375  0.867691 -2.401014 -0.760507
20409               1 -0.361034  0.037925 -0.768126  1.050861  0.912321
20410               0  0.117458  0.037925  2.737197 -0.790139  0.075907
20411               1 -0.839526  0.037925  1.902596  0.130361 -0.760507
20412               1 -0.361034 -0.497525  2.169669  0.130361 -0.760507

              parn      bhei  bheiuk     bhead  ...  arre36_6  arre36_7  \
idx_code                                        ...
0        -0.636012  0.685902     0.0  0.827566  ...         0         0
1        -0.636012 -0.622812     0.0 -1.218738  ...         0         0
2        -0.636012  0.685902     0.0  1.032196  ...         0         0
3        -0.636012 -0.149447     0.0  0.827566  ...         0         0
4         0.768667  1.521251     0.0  0.213674  ...         0         0
...            ...       ...     ...       ...  ...       ...       ...
20408    -0.636012  0.268227     0.0  0.622935  ...         0         0
20409     0.768667 -0.845572     0.0 -1.014108  ...         0         1
20410    -0.636012  1.660476     0.0  1.236826  ...         0         0
20411    -0.636012  1.382026     0.0  1.032196  ...         0         0
20412    -0.636012  1.938926     0.0  1.236826  ...         0         0

          pvl_1  pvl_3  pvl_2  seps_1  seps_2  seps_3  death_label  \
idx_code
0             1      0      0       1       0       0            0
1             1      0      0       0       1       0            0
2             1      0      0       1       0       0            0
3             0      1      0       0       1       0            0
4             1      0      0       1       0       0            0
...         ...    ...    ...     ...     ...     ...          ...
20408         1      0      0       0       1       0            0
20409         1      0      0       0       1       0            0
20410         1      0      0       1       0       0            0
20411         0      0      1       1       0       0            0
20412         0      0      1       1       0       0            0

          Cluster_Labels
idx_code
0                      1
1                      3
2                      1
3                      1
4                      4
...                  ...
20408                  1
20409                  3
20410                  1
20411                  1
20412                  1

[20352 rows x 113 columns]
          sex_sys_val     birthdt        bird        admd  apgs1  apgs5  bwei  \
idx_code
0                   1  2013-12-18  2013-12-18  2013-12-18    4.0    5.0  1350
1                   1  2013-11-15  2013-11-15  2013-11-15    4.0    5.0   790
2                   1  2013-11-15  2013-11-15  2013-11-15    5.0    6.0  1400
3                   1  2013-11-15  2013-11-15  2013-11-15    6.0    7.0  1340
4                   1  2013-11-11  2013-11-11  2013-11-11    4.0    5.0  1240
...               ...         ...         ...         ...    ...    ...   ...
20408               1  2022-11-28  2022-11-28  2022-11-28    5.0    8.0  1350
20409               1  2022-12-27  2022-12-27  2022-12-27    4.0    7.0   860
20410               0  2022-12-01  2022-12-01  2022-12-01    5.0    7.0  1910
20411               1  2022-11-30  2022-11-30  2022-11-30    3.0    7.0  1660
20412               1  2022-11-30  2022-11-30  2022-11-30    4.0    6.0  1740

          mage  gran  parn  ...  ntetoy_3  ntetoy_1  iperr_1  iperr_2  \
idx_code                    ...
0           29     1     0  ...         0         0        1        0
1           35     1     0  ...         0         0        1        0
2           26     1     0  ...         0         0        1        0
3           26     1     0  ...         0         0        1        0
4           36     4     1  ...         0         0        1        0
...        ...   ...   ...  ...       ...       ...      ...      ...
20408       23     1     0  ...         0         0        1        0
20409       38     3     1  ...         0         0        1        0
20410       30     2     0  ...         0         0        1        0
20411       34     1     0  ...         0         0        1        0
20412       34     1     0  ...         0         0        1        0

          iperr_3  iperr_4  iperroy_1  iperroy_4  iperroy_3  iperroy_2
idx_code
0               0        0          1          0          0          0
1               0        0          1          0          0          0
2               0        0          1          0          0          0
3               0        0          1          0          0          0
4               0        0          1          0          0          0
...           ...      ...        ...        ...        ...        ...
20408           0        0          1          0          0          0
20409           0        0          1          0          0          0
20410           0        0          1          0          0          0
20411           0        0          1          0          0          0
20412           0        0          1          0          0          0

[20352 rows x 162 columns]

/home/bami/anaconda3/envs/JHA_qiime2/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3165: DtypeWarning: Columns (22) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [6]:
## 특정 칼럼의 값을 가진 인원만 사용

# col_name1 = 'iperr_2'
# col_name2 = 'ntet_1'
col_name = 'iperr_2'
value = 1

# df = df[(df[col_name1] == value) | (df[col_name2] == value)]    # 'OR' condition
df = df[df[col_name] == value]
num_rows = df.shape[0]
num_cols = df.shape[1]
summary_df = pd.DataFrame({
    'n_participants': [num_rows],
    'n_features': [num_cols]
})
file_name = col_name.split('_')[0] + '_Pos_DataSummary'

summary_df.to_csv(f"{out}/{file_name}.csv", index=False)
print(f"Data summary has been saved: {out}/{file_name}.csv")

df

Data summary has been saved: /media/bami/d4960d77-e5f3-4877-a333-26e637be3a0e/JHA/24-07_nedis/KNN/Clustering/M15_dataset08/2_SurvOnly/1_ALL/iperr_Pos_DataSummary.csv

,sex_sys_val,birthdt,bird,admd,apgs1,apgs5,bwei,mage,gran,parn,...,ntetoy_3,ntetoy_1,iperr_1,iperr_2,iperr_3,iperr_4,iperroy_1,iperroy_4,iperroy_3,iperroy_2
idx_code,,,,,,,,,,,,,,,,,,,,,
109,0,2013-07-21,2013-07-21,2013-08-03,3.0,4.0,922,38,3,2,...,1,0,0,1,0,0,0,1,0,0
202,1,2013-12-19,2013-12-19,2013-12-19,5.0,7.0,1128,32,1,0,...,0,0,0,1,0,0,0,0,1,0
243,0,2013-10-23,2013-10-23,2013-10-23,6.0,8.0,1200,22,1,0,...,0,0,0,1,0,0,0,0,1,0
250,0,2013-08-06,2013-08-06,2013-08-06,3.0,5.0,690,36,3,1,...,0,0,0,1,0,0,0,0,1,0
279,0,2013-08-23,2013-08-23,2013-08-23,1.0,4.0,1150,33,1,0,...,0,0,0,1,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19978,1,2022-04-16,2022-04-16,2022-04-16,4.0,7.0,850,30,1,0,...,0,0,0,1,0,0,0,0,1,0
20126,1,2022-07-15,2022-07-15,2022-07-15,5.0,7.0,800,25,2,1,...,0,0,0,1,0,0,0,0,1,0
20225,1,2022-06-05,2022-06-05,2022-06-05,2.0,4.0,580,34,1,0,...,0,0,0,1,0,0,0,0,1,0
20238,0,2022-07-26,2022-07-26,2022-07-28,7.0,9.0,740,30,1,0,...,0,0,0,1,0,0,0,0,1,0
20308,1,2022-08-09,2022-08-09,2022-08-09,3.0,8.0,815,34,2,1,...,0,0,0,1,0,0,0,1,0,0

In [8]:
# ntet_1
# iperr_2
# death36

# 생존과 사망 비율 계산 (%)
death_label_ratio = df['iperr_2'].value_counts(normalize=True) * 100
# 생존(0)과 사망(1) 비율 각각 출력
survived_ratio = death_label_ratio[0]  # 생존 비율
died_ratio = death_label_ratio[1]      # 사망 비율
# 출력
print("[1-1, IPERR POS]")
print("[df_scd (Processed df)]")
print(f"Negatives (0): {survived_ratio:.2f}%")
print(f"Negatives / Total : {len(df[df['iperr_2'] == 0])} / {len(df['iperr_2'])}")
print("&")
print(f"Positives (1): {died_ratio:.2f}%")
print(f"Positives / Total : {len(df[df['iperr_2'] == 1])} / {len(df['iperr_2'])}")
print()


# 생존과 사망 비율 계산 (%)
death_label_ratio = df['ntet_1'].value_counts(normalize=True) * 100
# 생존(0)과 사망(1) 비율 각각 출력
survived_ratio = death_label_ratio[0]  # 생존 비율
died_ratio = death_label_ratio[1]      # 사망 비율
# 출력
print("[1-2, NTET POS]")
print("[df_scd (Processed df)]")
print(f"Negatives (0): {survived_ratio:.2f}%")
print(f"Negatives / Total : {len(df[df['ntet_1'] == 0])} / {len(df['ntet_1'])}")
print("&")
print(f"Positives (1): {died_ratio:.2f}%")
print(f"Positives / Total : {len(df[df['ntet_1'] == 1])} / {len(df['ntet_1'])}")
print()


# 생존과 사망 비율 계산 (%)
death_label_ratio = df['death_label'].value_counts(normalize=True) * 100
# 생존(0)과 사망(1) 비율 각각 출력
survived_ratio = death_label_ratio[0]  # 생존 비율
died_ratio = death_label_ratio[1]      # 사망 비율
# 출력
print("[2]")
print("[df_scd (Processed df)]")
print(f"Survived (0): {survived_ratio:.2f}%")
print(f"Survived / Total : {len(df[df['death_label'] == 0])} / {len(df['death_label'])}")
print("&")
print(f"Died (1): {died_ratio:.2f}%")
print(f"Death / Total : {len(df[df['death_label'] == 1])} / {len(df['death_label'])}")
print()




## IPERR + NTET BOTH
conditioned_participants = len(df[(df['iperr_2'] == 1) & (df['ntet_1'] == 1)])
# 전체 데이터의 인원 수
total_participants = len(df)
# 조건에 맞는 데이터의 전체 데이터 대비 비율
conditioned_ratio = (conditioned_participants / total_participants) * 100
# 출력
print("[IPERR+NTET BOTH]")
print("[df_scd (Processed df)]")
print(f"Conditioned Participants (1 in both iperr_2 and ntet_1): {conditioned_participants}")
print(f"Conditioned Participants / Total : {conditioned_participants} / {total_participants} ({conditioned_ratio:.2f}%)")

[1-1, IPERR POS]
[df_scd (Processed df)]
Negatives (0): 97.75%
Negatives / Total : 19894 / 20352
&
Positives (1): 2.25%
Positives / Total : 458 / 20352

[1-2, NTET POS]
[df_scd (Processed df)]
Negatives (0): 93.70%
Negatives / Total : 19070 / 20352
&
Positives (1): 6.30%
Positives / Total : 1282 / 20352

[2]
[df_scd (Processed df)]
Survived (0): 87.27%
Survived / Total : 17761 / 20352
&
Died (1): 12.73%
Death / Total : 2591 / 20352

[IPERR+NTET BOTH]
[df_scd (Processed df)]
Conditioned Participants (1 in both iperr_2 and ntet_1): 146
Conditioned Participants / Total : 146 / 20352 (0.72%)

In [9]:
print(df_scd['Cluster_Labels'].value_counts().sort_index())
print(df_scd.isnull().sum())

1    8009
2    2392
3    2908
4    7043
Name: Cluster_Labels, dtype: int64
sex_sys_val       0
apgs1             0
apgs5             0
bwei              0
mage              0
                 ..
seps_1            0
seps_2            0
seps_3            0
death_label       0
Cluster_Labels    0
Length: 113, dtype: int64

In [10]:
df_scd.to_csv(os.path.join(save_dir, "df_scd_clustered.csv"))

In [11]:
## Merge Cluster_Labels to original dataframe
df_combined = df.merge(df_scd[['Cluster_Labels']]
                       , left_index=True, right_index=True
                       , how='left'
                      )
df_combined

,sex_sys_val,birthdt,bird,admd,apgs1,apgs5,bwei,mage,gran,parn,...,ntetoy_1,iperr_1,iperr_2,iperr_3,iperr_4,iperroy_1,iperroy_4,iperroy_3,iperroy_2,Cluster_Labels
idx_code,,,,,,,,,,,,,,,,,,,,,
0,1,2013-12-18,2013-12-18,2013-12-18,4.0,5.0,1350,29,1,0,...,0,1,0,0,0,1,0,0,0,1
1,1,2013-11-15,2013-11-15,2013-11-15,4.0,5.0,790,35,1,0,...,0,1,0,0,0,1,0,0,0,3
2,1,2013-11-15,2013-11-15,2013-11-15,5.0,6.0,1400,26,1,0,...,0,1,0,0,0,1,0,0,0,1
3,1,2013-11-15,2013-11-15,2013-11-15,6.0,7.0,1340,26,1,0,...,0,1,0,0,0,1,0,0,0,1
4,1,2013-11-11,2013-11-11,2013-11-11,4.0,5.0,1240,36,4,1,...,0,1,0,0,0,1,0,0,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20408,1,2022-11-28,2022-11-28,2022-11-28,5.0,8.0,1350,23,1,0,...,0,1,0,0,0,1,0,0,0,1
20409,1,2022-12-27,2022-12-27,2022-12-27,4.0,7.0,860,38,3,1,...,0,1,0,0,0,1,0,0,0,3
20410,0,2022-12-01,2022-12-01,2022-12-01,5.0,7.0,1910,30,2,0,...,0,1,0,0,0,1,0,0,0,1
20411,1,2022-11-30,2022-11-30,2022-11-30,3.0,7.0,1660,34,1,0,...,0,1,0,0,0,1,0,0,0,1
20412,1,2022-11-30,2022-11-30,2022-11-30,4.0,6.0,1740,34,1,0,...,0,1,0,0,0,1,0,0,0,1

In [19]:
for column in df_combined.columns:
    print(f"칼럼 이름: {column}")
    print(f"데이터 타입: {df_combined[column].dtype}")
    print(f"유니크한 값:")
    print(df_combined[column].unique())
    print("-" * 40)

칼럼 이름: sex_sys_val
데이터 타입: int64
유니크한 값:
[1 0]
----------------------------------------
칼럼 이름: birthdt
데이터 타입: object
유니크한 값:
['2013-12-18' '2013-11-15' '2013-11-11' ... '2022-05-05' '2022-07-09'
 '2022-06-19']
----------------------------------------
칼럼 이름: bird
데이터 타입: object
유니크한 값:
['2013-12-18' '2013-11-15' '2013-11-11' ... '2022-05-05' '2022-07-09'
 '2022-06-19']
----------------------------------------
칼럼 이름: admd
데이터 타입: object
유니크한 값:
['2013-12-18' '2013-11-15' '2013-11-11' ... '2022-05-05' '2022-07-09'
 '2022-06-19']
----------------------------------------
칼럼 이름: apgs1
데이터 타입: float64
유니크한 값:
[ 4.          5.          6.          3.          7.          1.
  9.          8.          2.          4.75271096  0.         10.        ]
----------------------------------------
칼럼 이름: apgs5
데이터 타입: float64
유니크한 값:
[ 5.          6.          7.          8.          4.          9.
  1.          3.         10.          2.          6.92736054  0.        ]
----------------------------------------
칼럼 이름: bwei
데이터 타입: int64
유니크한 값:
[1350  790 1400 1340 1240  810 1300 1380  990 1180 1475 1450 1485  960
  910  730 1370 1205 1440 1390 1480 1290 1210 1455 1200 1360 1470 1015
  860  865 1130 1090  920 1260 1220 1320  980  660  600 1270  940 1080
 1190 1490 1040  930  670 1160  480 1330 1250 1460 1310  473  840  850
 1140  610  950 1070 1060  720  680  770 1170  710 1061 1002 1120 1020
  922 1037 1031  765  438 1243  880 1306 1472  708 1376  924  970 1150
 1245 1065 1100 1445  890  780  640  731 1452  756  714  719 1047 1312
  726 1013  483 1420 1498 1124  550 1206  782  936 1074 1128 1408 1484
 1410  740 1110  760  470  870 1230  800  690  590 1378  900 1010 1286
 1248 1194 1356  750  530 1342 1430 1354 1050 1280  515  510  855 1325
  955  995  645  650  830  580  570  430  540  820  875  460  490  520
 1000  400  700 1030  630  560  620 1255  320  440  500 1355 1495  380
  816  846  932 1165 1375  805  533  420  705  775  915  849  615  885
 1211 1244  839 1405 1466 1098 1025 1104 1365 1185  965 1315 1285  575
  585  735 1295  935 1335  925  633 1113  776 1352 1048  755  953  819
 1372 1387 1457 1146 1225 1252  886  897  946  512  519  657  717  736
 1006 1014 1017 1476 1085  951 1436  801  777  988  967  879 1486  458
 1276 1151  732 1439 1195  835 1499  370 1453  929 1444  934 1363  964
  337 1066 1407  598 1028 1235  652  966  675  794  814  592 1398 1036
 1446 1496 1294 1024 1435  795  789  535  815  703  300 1305  330 1482
  410 1454 1345 1095 1145  655  878  545 1395  450  310  905  495  825
 1005  671 1409 1441  595 1045  853  945 1334  833 1075 1115 1275 1415
 1385  745 1402 1142 1176 1442 1247 1425  704 1382 1035 1249 1093  405
 1041  574  493 1229  709 1344  831  894  567  416 1062 1122 1392 1026
 1234  565 1049 1327  857  658 1012 1181  812 1246  842 1136  649  974
  618 1388 1198  943  902  340  975  665 1175 1155 1298  701  639 1167
 1241  804 1261 1016 1326 1296 1491  496 1226 1196  762 1277 1412 1418
 1414 1364 1336 1464 1094 1386 1254  845 1278 1494 1288  754  501  494
 1215 1123 1465  350  635  390  433  555  985 1105 1055  685 1471  695
 1487 1463  505 1483 1406  725 1129 1362 1125 1156 1228 1202 1456  654
  949  972  764  739 1153  673 1272  917  753 1071  554  613 1309  698
  989  454  636 1059  558  772  506  696 1148  863 1201 1149 1052 1492
  507 1238  869 1329 1297  543 1267 1358 1119 1434 1438  724 1112  360
 1135 1426 1302  548  767  694 1279  707  911 1008  638 1314 1046 1056
 1469  434  991  672 1042 1265  702  914  475  715 1266 1116  898  579
 1368 1282  903  844  544  499 1332 1349  504  913  492  817 1203  752
  856  909  787  757  318  758  959 1213  566 1462  662  798  977 1019
 1253 1107 1043  895  587  596 1322  868  466 1383 1157 1328  918  307
 1134 1216 1224 1064  766  467  451 1389  616 1154  528 1227  749  557
 1068  674  485  551  605 1481  534  761  968  956  912 1428  901  346
  663  549  513 1419  907 1377  896  602  682  877  586  937 1318  848
  723 1089  948  996  926 1172  552 1373 1474  634 1177  854  711 1258
  759 1404 1478 1222  302  455  821 1421 1396 1489  785  531  328 1162
 1158 1007 1447 1347 1111  893  503  568 1178  889  793  887  978  818
  923 1034 1021 1022  376 1004 1204  332 1443 1416 1077 1171  609  465
 1304 1084 1374 1029  927  982 1058 1289  743 1221 1018  593 1139 1044
  524  984  392 1051  641  345  569  799  963 1381 1236 1351 1479 1208
  617  837 1431  921  365  604 1323  612  983 1161 1078  796 1001  546
 1393  526 1283 1338 1308  716  746  691 1319  763  611 1257 1346 1379
  619  806  788  938  572 1063  688  556  827 1114 1331  811  882 1103
  873  642 1324  668  497  608  564  421  647  973  588 1424 1497  338
  737 1144  684 1039 1493  677  713  824 1159 1038  601  621  741  998
 1009 1237 1458 1086 1449  941  931  516 1092  689 1366  783 1073 1281
  986 1088  325 1477  981  957  942  876  581  866  656 1292  733 1287
  692  452  469  631 1321  884  355 1214  625 1301  523  859 1117 1173
 1251 1164 1032 1670 1540 1660 1610 1740 1550 1520 1500 1650 1980 1920
 1620 1570 1580 1770 1810 1830 1630 1690 1950 1730 1468  872 1510 1880
 1780 1524 1759 1552 1860  482 1870 1712 1534 1264 1909  742  944 1926
 1545 1873 1718  539 1579  666  525  916 1273 1054 1850 1820 1800 1567
 1750 1560  797  624 1640 1523 1700 1027 1868 1760 1960 1530 1600 1625
 1174 1652 1764 1528 1218 1890 1790 1665 1535 1512 1900 1710 1590 1930
 1840 1910 1313 1432  401 1461 1773 1574 1680 1720 1835  928  447  374
  999 1316  559  429  532  502 1756 1990 1940 2000 1945 1765 1506 1586
 1538 1722 1549 1357 1970 1752 1657 1768  408  541 1003 1564  939 1391
 1934 1531 1076  511 1555 1505]
----------------------------------------
칼럼 이름: mage
데이터 타입: int64
유니크한 값:
[29 35 26 36 32 42 33 30 31 28 37 34 41 25 20 38 39 27 24 19 43 21 23 40
 22 44 47 45 18 16 46 15 13 49 17 48 14 10 51 50]
----------------------------------------
칼럼 이름: gran
데이터 타입: int64
유니크한 값:
[ 1  4  2  3  5  7  6 10  8  9 13 11 16 14 12 29]
----------------------------------------
칼럼 이름: parn
데이터 타입: int64
유니크한 값:
[0 1 2 3 4 9 5 8 6 7]
----------------------------------------
칼럼 이름: bhei
데이터 타입: float64
유니크한 값:
[39.        34.3       36.        42.        38.5       32.
 40.5       34.        38.        41.        35.5       35.
 29.5       40.        31.        41.5       37.        36.5
 39.5       30.        24.5       33.        30.5       36.2
 33.5       25.5       36.5344407 38.8       37.8       34.7
 37.1       27.        34.5       39.2       42.5       35.2
 35.6       40.7       37.5       28.6       43.        28.
 29.        26.        31.5       32.5       31.8       43.5
 37.2       28.5       27.5       38.4       36.3       35.1
 40.8       33.6       32.7       45.        23.        32.8
 39.3       32.3       41.2       44.        25.        38.2
 36.4       28.2       36.8       34.2       39.4       41.3
 33.7       35.8       31.4       48.        30.8       42.2
 41.4       37.6       38.3       29.7       33.8       30.4
 36.6       46.        37.3       41.7       22.        42.8
 40.3       38.1       31.2       25.7       24.        38.7
 23.5       41.1       34.8       39.8       27.8       32.1
 35.3       31.7       40.2       30.2       37.7       40.6
 26.5       45.5       34.4       28.8       39.7       44.5
 46.5       44.3       47.        35.4       42.3       27.1
 33.2       22.2       30.6       34.6       47.7       37.4
 26.1       33.3       31.9       41.8       36.1       31.3
 40.9       30.3       34.1       38.6       19.5       20.
 29.2       32.4       28.3       27.2       29.3       40.4
 36.7       37.9       27.3       35.7       44.8       39.6
 32.6       32.2       41.9       33.4       42.6       38.9
 25.3       34.9       29.4       49.        42.4       43.6
 21.        32.9       39.9       29.8       21.5       33.9
 36.9       31.6       29.9       30.7       41.6       24.2
 29.1       22.5       20.3       43.2       39.1       33.1
 23.3       42.9       42.7       26.6       42.1       40.1
 43.8      ]
----------------------------------------
칼럼 이름: bheiuk
데이터 타입: float64
유니크한 값:
[0. 1.]
----------------------------------------
칼럼 이름: bhead
데이터 타입: float64
유니크한 값:
[28.         23.         28.5        26.5        29.5        28.3
 24.5        30.         25.         29.         24.         27.5
 30.5        27.         25.5        31.         23.5        36.
 22.5        32.         22.         21.         26.         19.
 21.5        22.3        25.7        20.5        25.97613707 27.3
 29.1        23.3        28.4        25.6        29.2        25.4
 22.6        25.3        28.2        26.8        27.2        20.
 27.4        30.3        24.2        23.2        20.9        29.3
 18.5        24.7        25.8        23.9        26.1        24.8
 22.2        21.3        23.1        24.3        31.5        20.7
 26.2        19.5        23.6        21.6        27.7        26.6
 27.6        26.4        34.2        31.3        22.8        20.2
 35.5        28.8        25.2        29.4        19.8        27.8
 26.3        23.8        21.8        23.7        28.6        29.7
 28.7        26.7        28.1        30.2        24.6        20.3
 23.4        27.1        24.4        33.5        22.7        27.9
 21.4        29.8        24.1        20.6        19.7        28.9
 32.5        22.9        21.7        24.9        29.9        25.1
 18.         33.         21.2        20.8        22.4        25.9
 17.5        38.         21.9        30.4        18.7        30.1
 34.         31.2        20.1        26.9        29.6        19.3
 19.4        18.3        17.         30.7        20.4        19.9
 32.7        19.2        19.6        22.1        18.6        21.1
 34.5        16.         30.6        35.         14.5        31.6
 32.6        37.2        18.8        30.8       ]
----------------------------------------
칼럼 이름: bheaduk
데이터 타입: float64
유니크한 값:
[0. 1.]
----------------------------------------
칼럼 이름: btem
데이터 타입: float64
유니크한 값:
[36.4        36.5        36.6        37.         35.6        36.8
 36.7        36.2        34.7        35.3        36.1        36.
 36.3        35.4        35.9        35.7        35.         35.5
 38.         36.20092068 35.8        34.8        35.2        35.1
 34.5        37.1        34.         36.9        37.6        33.
 37.2        33.8        34.3        34.4        37.4        37.5
 34.9        34.6        34.2        34.1        33.4        37.3
 33.5        33.1        33.6        33.2        32.7        33.7
 33.9        32.3        37.9        37.8        37.7        32.1
 38.2        33.3        32.4        32.5        32.6        32.9
 32.2        38.4        31.9        38.1        32.         38.8
 32.8        31.3        38.3        38.7        38.5        38.6
 31.        ]
----------------------------------------
칼럼 이름: btemuk
데이터 타입: float64
유니크한 값:
[0. 1.]
----------------------------------------
칼럼 이름: bbph
데이터 타입: float64
유니크한 값:
[7.35       7.28       7.42       7.49       7.36       7.3
 7.21       7.1        7.44       7.31       7.46       7.33
 7.24       7.18       7.4        7.48       7.29       7.53
 7.34       7.23       7.25       7.2        7.06       7.02
 7.04       7.11       7.41       7.43       7.26155799 7.26
 7.32       7.39       7.19       7.27       7.09       7.13
 6.82       6.98       7.16       7.38       6.88       7.08
 7.22       6.97       7.45       7.37       7.17       7.05
 7.52       7.14       7.01       7.5        7.07       7.47
 7.03       7.15       6.9        6.99       7.12       7.57
 6.7        6.64       6.8        7.         6.87       7.55
 6.74       7.51       6.66       6.89       6.96       6.86
 6.84       6.95       7.54       6.92       6.76       6.5
 7.58       6.54       6.91       6.93       6.71       6.94
 6.77       7.65       6.83       7.59       6.75       6.85
 6.81       7.56       7.72       6.65       6.56       6.63
 7.63       6.57       6.67       6.55       7.68       6.73
 7.69       7.6        6.79       7.66       6.68       6.69
 7.62       6.17       6.61       6.51       6.78       6.59
 6.72      ]
----------------------------------------
칼럼 이름: bbphuk
데이터 타입: float64
유니크한 값:
[0. 1.]
----------------------------------------
칼럼 이름: bbbe
데이터 타입: float64
유니크한 값:
[ -5.3         -1.7          1.5         -3.9         -2.3
  -5.4         -9.2         -6.8          1.          -3.5
   1.8         -1.8         -4.4         -2.1         -7.2
 -10.          -0.2         -1.3         -1.2         -1.6
  -4.9         -3.7         -3.3         -4.6         -4.3
  -7.5        -11.4        -12.6         -2.          -5.2
   0.1        -13.          -9.1         -6.7         -2.8
  -2.9         -5.05779705 -15.2         -4.7         -3.
  -3.6         -5.1         -4.2         -8.          -0.8
  -5.9         -3.8         -4.1         -1.5         -6.2
 -10.1         -9.8         -6.          -6.1         -1.
  -3.1         -5.7         -7.1        -13.1         -9.
  -1.1        -11.8         -8.2         -3.2        -12.1
 -21.4         -9.7        -10.6        -20.         -15.6
  -9.5        -11.5         -6.4         -4.5        -17.
  -4.           2.           5.           1.1         -8.1
  -5.6        -17.4         -4.8        -10.2         -2.5
  -7.3          2.4        -12.9         -5.5         -8.8
 -12.4        -10.7         -9.3         -8.4        -10.3
  -3.4         -7.7         -1.9         -7.         -16.
  -5.          -0.           3.         -19.         -15.
 -18.         -11.          -2.4          0.6          0.2
 -11.9         -2.7         -2.6         -0.4          2.2
   1.9          4.          -9.9          0.8         -6.9
   2.1         -6.3         -2.2         -0.7        -14.
 -12.          -0.5         -5.8          0.7          1.2
 -14.3         -8.7        -12.7        -10.5        -11.7
  -0.3         -6.6         -7.4        -11.3          3.1
   4.4          2.3          0.5        -13.6         -6.5
  -8.3         -1.4        -14.1         -0.9        -18.3
  -8.6         -7.8         -0.6        -15.9         -9.6
 -18.7        -13.5        -13.4         -8.9        -11.6
  -0.1        -14.9        -19.1        -15.7         -7.9
  11.6          1.4        -10.8        -23.         -19.3
   0.9        -12.2         -8.5          5.5          3.6
   2.8          4.6          1.7          0.4          2.7
 -14.7        -10.4        -13.8        -10.9        -26.
 -16.6        -12.3         -9.4        -13.2          0.3
  -7.6        -16.7          2.6        -17.5          1.3
 -24.         -11.1          1.6          4.3          5.9
 -15.3        -20.5        -17.2          4.8        -17.8
 -20.8        -16.3        -15.5        -13.7        -18.9
 -19.4        -16.5          3.7        -16.4        -16.1
 -12.8          2.5         15.8          5.8          5.7
 -17.1        -23.4        -14.4        -19.9        -22.
 -21.         -13.3        -20.3          4.1        -21.2
 -11.2        -16.8        -15.8        -17.3        -21.1
 -15.1        -21.7        -21.5        -20.2        -14.5
   3.8        -22.9        -12.5        -13.9        -14.6
   3.3          6.7        -18.8          5.6          6.8
 -25.5        -20.1        -17.7        -14.2        -24.1
 -25.           4.2        -21.6        -19.2        -17.9
 -21.8        -18.2          3.4          7.1        -14.8
 -17.6        -25.1        -15.4        -22.2        -19.5
 -24.8        -23.6        -18.4         11.           2.9
 -22.5          3.9        -16.2        -23.9        -24.2
   4.5        -25.2        -20.6          3.5        -20.9
 -21.3          7.         -19.8         11.9          3.2
 -22.6        -16.9        -27.           8.8          9.2
   6.4        -18.1          8.6          5.3          7.5
  13.2         13.         -26.4          5.2        -24.9
 -19.7        -29.         -24.5        -28.           9.
   4.9        -22.8          7.9         24.6         15.
  29.          22.           8.         -26.9          6.1
 -18.6          8.1          5.4        -22.3        -20.4
   6.         -20.7       ]
----------------------------------------
칼럼 이름: bbbeuk
데이터 타입: float64
유니크한 값:
[0. 1.]
----------------------------------------
칼럼 이름: sftun
데이터 타입: float64
유니크한 값:
[2. 1. 0. 3. 4. 5. 6. 7. 9.]
----------------------------------------
칼럼 이름: date362
데이터 타입: object
유니크한 값:
[nan '2021-12-21' '2022-01-03' '2022-01-06' '2022-01-26' '2022-01-14'
 '2022-01-29' '2021-12-13' '2021-12-24' '2021-04-30' '2021-07-06'
 '2022-01-20' '2021-05-29' '2021-06-06' '2021-07-07' '2022-01-09'
 '2022-01-11' '2021-12-31' '2021-12-09' '2021-12-14' '2021-12-20'
 '2022-01-12' '2021-12-28' '2022-01-27' '2022-02-15' '2022-01-31'
 '2022-02-05' '2022-01-17' '2021-01-10' '2021-02-10' '2021-06-17'
 '2021-06-16' '2021-05-31' '2021-06-02' '2021-08-25' '2021-08-10'
 '2021-07-23' '2021-10-02' '2021-09-27' '2021-10-25' '2021-11-17'
 '2021-11-22' '2022-02-01' '2021-11-25' '2022-01-28' '2021-12-08'
 '2022-02-04' '2021-11-29' '2021-12-29' '2021-12-17' '2022-02-09'
 '2022-03-08' '2022-02-16' '2022-02-18' '2022-02-11' '2022-03-19'
 '2021-06-30' '2021-12-07' '2021-12-25' '2021-11-28' '2021-11-12'
 '2022-02-26' '2022-01-13' '2022-01-18' '2022-02-12' '2022-03-22'
 '2022-02-19' '2022-02-23' '2021-05-05' '2021-04-05' '2021-03-24'
 '2021-05-12' '2021-07-08' '2021-06-05' '2021-07-31' '2021-08-07'
 '2021-08-21' '2021-10-08' '2021-12-02' '2021-09-17' '2021-07-04'
 '2021-10-22' '2021-11-02' '2022-01-07' '2021-11-15' '2022-02-08'
 '2021-09-03' '2021-11-13' '2021-12-05' '2022-01-04' '2021-04-21'
 '2021-06-12' '2021-06-27' '2021-07-30' '2021-09-10' '2021-10-12'
 '2021-10-23' '2022-02-17' '2021-05-14' '2021-03-14' '2021-03-20'
 '2021-03-27' '2021-04-17' '2021-03-31' '2021-06-13' '2021-06-26'
 '2021-07-09' '2021-08-20' '2021-08-03' '2021-10-06' '2021-09-15'
 '2021-09-11' '2022-02-22' '2022-01-21' '2022-02-06' '2021-12-27'
 '2022-01-19' '2021-12-10' '2021-12-01' '2022-01-24' '2022-02-03'
 '2021-12-18' '2021-12-11' '2021-12-23' '2022-02-24' '2022-01-15'
 '2022-03-07' '2021-09-06' '2021-11-04' '2022-03-23' '2022-03-12'
 '2022-06-11' '2022-07-06' '2022-07-30' '2022-08-02' '2022-09-28'
 '2022-11-11' '2022-11-26' '2022-11-22' '2022-12-21' '2023-01-28'
 '2023-02-08' '2023-02-06' '2023-01-21' '2023-01-07' '2022-03-28'
 '2022-04-01' '2022-03-30' '2022-04-15' '2022-05-30' '2022-05-25'
 '2022-07-10' '2022-06-20' '2022-05-26' '2022-06-14' '2022-08-05'
 '2022-06-21' '2022-07-02' '2022-06-28' '2022-07-29' '2022-08-15'
 '2022-08-23' '2022-09-03' '2022-09-11' '2022-11-08' '2022-11-17'
 '2022-11-25' '2022-12-07' '2023-02-05' '2022-12-26' '2023-01-31'
 '2023-01-15' '2022-03-16' '2022-04-21' '2022-04-30' '2022-04-26'
 '2022-06-29' '2022-09-06' '2022-10-04' '2022-10-09' '2022-11-23'
 '2022-12-06' '2023-01-09' '2022-03-13' '2022-03-01' '2022-04-11'
 '2022-05-15' '2022-07-05' '2022-06-06' '2022-07-13' '2022-07-18'
 '2022-09-01' '2022-09-12' '2022-08-25' '2022-07-31' '2022-08-04'
 '2022-08-18' '2022-09-10' '2022-09-27' '2022-11-05' '2022-10-29'
 '2022-12-22' '2022-10-13' '2022-12-31' '2022-12-12' '2023-01-16'
 '2023-02-07' '2023-01-20' '2023-01-11' '2023-02-17' '2023-01-29'
 '2023-01-14' '2022-03-02' '2022-03-03' '2022-02-25' '2022-04-03'
 '2022-04-04' '2022-03-31' '2022-03-24' '2022-05-05' '2022-03-29'
 '2022-04-18' '2022-04-24' '2022-05-02' '2022-04-06' '2022-06-02'
 '2022-06-19' '2022-05-16' '2022-06-22' '2022-06-17' '2022-07-20'
 '2022-07-11' '2022-06-16' '2022-07-23' '2022-08-16' '2022-07-28'
 '2022-07-25' '2022-09-18' '2022-08-22' '2022-10-06' '2022-10-15'
 '2022-11-02' '2022-10-02' '2022-09-25' '2022-09-16' '2022-11-06'
 '2022-10-26' '2022-10-22' '2022-12-08' '2022-11-27' '2023-01-06'
 '2023-01-19' '2023-01-13' '2023-03-17' '2022-01-23' '2022-03-14'
 '2022-05-06' '2022-06-01' '2022-06-26' '2022-09-15' '2022-09-07'
 '2022-10-21' '2022-11-29' '2022-11-16' '2023-02-02' '2023-02-22'
 '2022-10-16' '2022-10-31' '2022-11-07' '2022-12-14' '2022-12-20'

In [12]:
df_combined.to_csv(os.path.join(save_dir, "KNN_df_combined.csv"))

In [13]:
# WILCOXON TEST

# Declare input data
input_df = df_combined

# 고유 클러스터 값과 클러스터 수 계산
unique_clusters = input_df['Cluster_Labels'].unique()
num_clusters = len(unique_clusters)

# 통계 및 p-값 저장용 DataFrame 생성
stats_df = pd.DataFrame()
p_values_df = pd.DataFrame()

# 각 클러스터 및 변수에 대한 계산
for i in unique_clusters:
    cluster_data = input_df[input_df['Cluster_Labels'] == i]
    outside_data = input_df[input_df['Cluster_Labels'] != i]
    stats = {}
    p_values = {}

    for column in input_df.columns[:-1]:  # 마지막 'Cluster_Labels' 제외
        if column != 'Cluster_Labels' and is_numeric_dtype(input_df[column]):
            valid_cluster_data = cluster_data[column].dropna()
            valid_outside_data = outside_data[column].dropna()

            # 두 집단 모두에서 유효한 데이터가 존재하고 모든 값이 같지 않을 때만 계산
            if len(valid_cluster_data) > 0 and len(valid_outside_data) > 0 and pd.concat([valid_cluster_data, valid_outside_data]).nunique() > 1:
                u_stat, p_value = mannwhitneyu(valid_cluster_data, valid_outside_data, alternative='two-sided')
                mean_val = valid_cluster_data.mean()
                std_dev = valid_cluster_data.std()

                # 결과 저장
                stats[column] = f"{mean_val:.4f} ± {std_dev:.4f}"
                if p_value < 0.01:
                    formatted_p_value = f"{p_value:.4e}" if p_value < 0.0001 else f"{p_value:.4f}"
                    p_values[column] = formatted_p_value
                else:
                    p_values[column] = "n.s."
            else:
                stats[column] = "NaN ± NaN"
                p_values[column] = "n.s."

    stats_df[f'Cluster {i}'] = pd.Series(stats)
    p_values_df[f'Cluster {i}'] = pd.Series(p_values)

# 결과를 DataFrame으로 결합
combined_df = pd.DataFrame()
for i in unique_clusters:
    combined_stats = stats_df[f'Cluster {i}'] + " (" + p_values_df[f'Cluster {i}'] + ")"
    combined_df[f'Cluster {i}'] = combined_stats

# Cluster 열을 이름을 기준으로 정렬
combined_df = combined_df.reindex(sorted(combined_df.columns), axis=1)

# 결과 출력
print("Combined Mean, Standard Deviation and P-values:")
print(combined_df)

Combined Mean, Standard Deviation and P-values:
                                     Cluster 1  \
sex_sys_val       0.4675 ± 0.4990 (1.3851e-16)
apgs1             5.9020 ± 1.7950 (0.0000e+00)
apgs5             7.8803 ± 1.3124 (0.0000e+00)
bwei         1304.6117 ± 189.8241 (0.0000e+00)
mage                   33.4485 ± 4.3115 (n.s.)
...                                        ...
iperr_4                 0.0000 ± 0.0000 (n.s.)
iperroy_1         0.9971 ± 0.0535 (8.1546e-52)
iperroy_4         0.0004 ± 0.0194 (1.8439e-07)
iperroy_3         0.0025 ± 0.0499 (6.7980e-41)
iperroy_2         0.0000 ± 0.0000 (3.6388e-06)

                                    Cluster 2  \
sex_sys_val      0.5460 ± 0.4980 (9.4112e-06)
apgs1            3.0520 ± 1.8546 (0.0000e+00)
apgs5            5.2514 ± 2.2271 (0.0000e+00)
bwei         766.3654 ± 271.2368 (0.0000e+00)
mage                33.1810 ± 4.5972 (0.0097)
...                                       ...
iperr_4                0.0008 ± 0.0289 (n.s.)
iperroy_1        0.9444 ± 0.2292 (1.1681e-31)
iperroy_4        0.0092 ± 0.0955 (1.4919e-10)
iperroy_3        0.0364 ± 0.1873 (5.8626e-13)
iperroy_2        0.0100 ± 0.0997 (1.3634e-27)

                                    Cluster 3  \
sex_sys_val            0.5241 ± 0.4995 (n.s.)
apgs1           3.4860 ± 1.7420 (1.3436e-284)
apgs5           5.9194 ± 1.8475 (6.3352e-244)
bwei         778.9952 ± 191.8418 (0.0000e+00)
mage                  33.6296 ± 4.2174 (n.s.)
...                                       ...
iperr_4                0.0003 ± 0.0185 (n.s.)
iperroy_1        0.9384 ± 0.2404 (8.3885e-54)
iperroy_4        0.0072 ± 0.0847 (6.6900e-07)
iperroy_3        0.0519 ± 0.2219 (4.6596e-50)
iperroy_2              0.0024 ± 0.0490 (n.s.)

                                     Cluster 4
sex_sys_val           0.5214 ± 0.4996 (0.0002)
apgs1             4.5517 ± 1.8305 (2.5658e-28)
apgs5             6.8344 ± 1.6166 (6.5788e-28)
bwei         1084.5336 ± 224.1381 (1.4440e-14)
mage                   33.4213 ± 4.3450 (n.s.)
...                                        ...
iperr_4                 0.0006 ± 0.0238 (n.s.)
iperroy_1             0.9830 ± 0.1294 (0.0002)
iperroy_4             0.0014 ± 0.0377 (0.0083)
iperroy_3               0.0153 ± 0.1229 (n.s.)
iperroy_2             0.0003 ± 0.0169 (0.0006)

[148 rows x 4 columns]

In [14]:
combined_df.to_csv(os.path.join(save_dir, "KNN_df_combined_wilcoxon+p_val.csv")
                   , encoding='utf-8-sig'    # '±'표현을 위해 encoding='utf-8-sig' 사용
                  )

In [15]:
## DEATH RATIO
# 'Cluster_Labels'와 'death_label' 확인
def calculate_positive_rate(ipt_df, ipt_col):
    # 'Cluster_Labels'와 ipt_col 확인
    if 'Cluster_Labels' in ipt_df.columns and ipt_col in ipt_df.columns:
        results_df = pd.DataFrame()

        # 각 클러스터의 Positive Rate 계산
        for i in sorted(ipt_df['Cluster_Labels'].unique()):  # Cluster_Labels 번호 순서대로 정렬
            cluster_data = ipt_df[ipt_df['Cluster_Labels'] == i]
            total_count = cluster_data.shape[0]
            positive_count = (cluster_data[ipt_col] == 1).sum()
            negative_count = (cluster_data[ipt_col] == 0).sum()

            # 칼럼 이름에서 언더바 이후를 제거
            display_col = ipt_col.split('_')[0]

            # Positive Rate 계산
            positive_rate = (positive_count / total_count) * 100

            # 결과 저장
            results_df.loc[f'Cluster {i}', 'Total'] = total_count
            results_df.loc[f'Cluster {i}', f'{display_col}_Pos'] = positive_count
            results_df.loc[f'Cluster {i}', f'{display_col}_Neg'] = negative_count
            results_df.loc[f'Cluster {i}', 'Positive Rate'] = f"{positive_rate:.2f}%"
            results_df.loc[f'Cluster {i}', f'{display_col}_Pos / Total'] = f"{positive_count} / {total_count}"

        # 결과 출력
        return results_df
    else:
        return f"Dataframe does not contain required columns 'Cluster_Labels' and '{ipt_col}'"


# iperr_3
# iperr_4

# ntet_1
# iperr_2
# death36
cmr = calculate_positive_rate(df_combined, 'death_label')
cmr1 = calculate_positive_rate(df_combined, 'ntet_1')
cmr2 = calculate_positive_rate(df_combined, 'iperr_2')
print(cmr, cmr1, cmr2)

            Total  death_Pos  death_Neg Positive Rate death_Pos / Total
Cluster 1  8009.0       25.0     7984.0         0.31%         25 / 8009
Cluster 2  2392.0     2285.0      107.0        95.53%       2285 / 2392
Cluster 3  2908.0      171.0     2737.0         5.88%        171 / 2908
Cluster 4  7043.0      110.0     6933.0         1.56%        110 / 7043             Total  ntet_Pos  ntet_Neg Positive Rate ntet_Pos / Total
Cluster 1  8009.0     127.0    7882.0         1.59%       127 / 8009
Cluster 2  2392.0     344.0    2048.0        14.38%       344 / 2392
Cluster 3  2908.0     395.0    2513.0        13.58%       395 / 2908
Cluster 4  7043.0     416.0    6627.0         5.91%       416 / 7043             Total  iperr_Pos  iperr_Neg Positive Rate iperr_Pos / Total
Cluster 1  8009.0       23.0     7986.0         0.29%         23 / 8009
Cluster 2  2392.0      136.0     2256.0         5.69%        136 / 2392
Cluster 3  2908.0      179.0     2729.0         6.16%        179 / 2908
Cluster 4  7043.0      120.0     6923.0         1.70%        120 / 7043

In [16]:
cmr.to_csv(os.path.join(save_dir, "mortality_rate_results_death36.csv"), encoding='utf-8-sig')
cmr1.to_csv(os.path.join(save_dir, "mortality_rate_results_ntetPos.csv"), encoding='utf-8-sig')
cmr2.to_csv(os.path.join(save_dir, "mortality_rate_results_iperrPos.csv"), encoding='utf-8-sig')

In [17]:
# Result function : 'n' about 2+ Cols

def calculate_positive_rate(ipt_df, ipt_cols):
    # 'Cluster_Labels'와 ipt_cols가 존재하는지 확인
    if 'Cluster_Labels' in ipt_df.columns and all(col in ipt_df.columns for col in ipt_cols):
        results_df = pd.DataFrame()

        # 두 칼럼 전부 1인 경우를 Positive로 간주 ('And' Condition)
        ipt_df['combined_Positive'] = (ipt_df[ipt_cols[0]] == 1) & (ipt_df[ipt_cols[1]] == 1)

        # 각 클러스터별 Positive Rate 계산
        for i in sorted(ipt_df['Cluster_Labels'].unique()):  # Cluster_Labels 번호 순서대로 정렬
            cluster_data = ipt_df[ipt_df['Cluster_Labels'] == i]
            total_count = cluster_data.shape[0]
            positive_count = cluster_data['combined_Positive'].sum()
            negative_count = total_count - positive_count

            # 칼럼 이름 조합하여 표시
            display_col = "_and_".join([col.split('_')[0] for col in ipt_cols])

            # Positive Rate 계산
            positive_rate = (positive_count / total_count) * 100

            # 결과 저장
            results_df.loc[f'Cluster {i}', 'Total'] = total_count
            results_df.loc[f'Cluster {i}', f'{display_col}_Pos'] = positive_count
            results_df.loc[f'Cluster {i}', f'{display_col}_Neg'] = negative_count
            results_df.loc[f'Cluster {i}', 'Positive Rate'] = f"{positive_rate:.2f}%"
            results_df.loc[f'Cluster {i}', f'{display_col}_Pos / Total'] = f"{positive_count} / {total_count}"

        # 'combined_Positive' 칼럼 삭제 (원본 유지)
        ipt_df.drop(columns=['combined_Positive'], inplace=True)

        # 결과 출력
        return results_df
    else:
        return f"Dataframe does not contain required columns 'Cluster_Labels' and {ipt_cols}"

# 사용 예시
cmr3 = calculate_positive_rate(df_combined, ['ntet_1', 'iperr_2'])
print(cmr3)

            Total  ntet_and_iperr_Pos  ntet_and_iperr_Neg Positive Rate  \
Cluster 1  8009.0                 4.0              8005.0         0.05%
Cluster 2  2392.0                52.0              2340.0         2.17%
Cluster 3  2908.0                53.0              2855.0         1.82%
Cluster 4  7043.0                37.0              7006.0         0.53%

          ntet_and_iperr_Pos / Total
Cluster 1                   4 / 8009
Cluster 2                  52 / 2392
Cluster 3                  53 / 2908
Cluster 4                  37 / 7043

In [18]:
cmr3.to_csv(os.path.join(save_dir, "mortality_rate_results_iperr&ntet.csv"), encoding='utf-8-sig')